Missing error handler on `socket`. TypeError: (msg || "").replace is not a function   at /xxx/node_modules/karma/lib/reporter.js:45:23   at [object Object].onBrowserError (/xxx/node_modules/karma/lib/reporters/base.js:58:60)